#!/bin/sh
set -e

HTML=${HTML:-"pandoc --smart -t html"}
MAX_HEADER=${MAX_HEADER:-5000}

die() { >&2 echo $1; exit 1; }
body() { sed '1,/^$/d' $1; }
header() { sh -c "$(./notes env $2) sh -c 'echo \$$1'" 2>/dev/null; }
headers() { sed '/^$/q' $1 | head -c $MAX_HEADER; }

list() {
  [ $# -eq 0 ] && { printf ""; return; }

  for NOTE in $(ls -t $@); do paste -s -d"\t" - <<EOF
${NOTE%.md}.html
$(date -u -r $(stat -f %m $NOTE) +%FT%T+00:00)
$(header title $NOTE)
EOF
  done
}

env_() {
  if [ -n "$1" ]; then
    headers $1 | cat notes.conf.sh - | sed 's/^#.*$//' | paste -s -d' ' -
  else
    sed 's/^#.*$//' notes.conf.sh | paste -s -d' ' -
  fi
}

case $1 in
  atom)
    [ -n "$(header site_url index.md)" ] || die 'Have you set the site_url in notes.conf.sh?'
    list ${@:2} | sh -c "$(./notes env) ./notes-atom.sh"
    ;;
  index)
    $HTML index.md | sh -c "$(./notes env) ./notes-index.sh ${*:2}"
    ;;
  note)
    [ -n "$(header title $2)" ] || die "Have you set the title in $2?"
    body $2 | $HTML | sh -c "$(./notes env $2) ./notes-html.sh"
    ;;

  env) env_ $2 ;;
  header) header $2 $3 ;;
  ls) list ${@:2} ;;
  *) exit 1
esac
