#!/bin/sh
set -e

HTML=${HTML:-"pandoc -t html"}

case $1 in
  -h)
    echo "Usage: $0 -h | hello.md"
    ;;
  render)
    sh theme/html.sh
    ;;
  *)
    DEFAULTS=$(paste -s -d' ' - < noter.conf)
    HEADERS=$(sed '/^$/q' $1 | paste -s -d' ' -)
    case "$HEADERS" in
      *title=*) sh -c "sed '1,/^$/d' $1 | $HTML | $DEFAULTS $HEADERS $0 render $2" ;;
      *)
        >&2 echo "Required: title. (Missing from $1.)"
        exit 1
        ;;
    esac
    ;;
esac
